exclude: ^versioneer.py|^src/mda_core/_version.py
default_language_version:
  python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: name-tests-test
        args: ['--django']
    -   id: no-commit-to-branch
        args: [--branch, main, --branch, develop]

-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/roy-ht/pre-commit-jupyter
    rev: v1.2.1
    hooks:
      - id: jupyter-notebook-cleanup
        # args:
        #   - --remove-kernel-metadata
        #   - --pin-patterns
        #   - "[pin];[donotremove]"

-   repo: https://github.com/sondrelg/pep585-upgrade
    rev: 'v1.0'
    hooks:
      - id: upgrade-type-hints
