ip_address:
    primary_mcs: "192.168.10.102:9090"
    secondary_mcs: "192.168.10.102:9090"
    can_mcs: "172.16.8.65:9090"

instance : "FF6"
duration : 1 # hrs (last N hours of telemetry will b fetched )
