primary_mcs:
    ip_address: "http://192.168.10.119:8093/"
    instance : "FF03-primary"
secondary_mcs:
    ip_address: "http://192.168.10.132:8093/"
    instance : FF03-secondary
can_mcs:
    ip_address: "172.16.8.65:9090"

credentials:
    username: "subsystem"
    password: "iamffsubsystem"

duration : 1 # hrs (last N hours of telemetry will b fetched )
