primary_mcs:
    ip_address: "http://192.168.10.119:8096/"
    instance : "FF05-primary"
secondary_mcs:
    ip_address: "http://192.168.10.132:8096/"
    instance : FF05-secondary
can_mcs:
    ip_address: "172.16.8.65:9090"

credentials:
    username: "subsystem"
    password: "iamffsubsystem"

duration : 1 # hrs (last N hours of telemetry will b fetched )
